### ISSUE TITLE
Terminal doesn't show "results"

### ISSUE THREAD

**Issue by coristig** [yhat/rodeo#536] opened 2016-11-15 14:46 UTC
![image](https://cloud.githubusercontent.com/assets/7118371/20309992/2f6e3e5a-ab18-11e6-82a5-8462b4e7667f.png)

We should be printing the output of the `result` in the Terminal.
![image](https://cloud.githubusercontent.com/assets/7118371/20310008/3e3ee3f8-ab18-11e6-9885-4c60e373e101.png)

**Comment by TakenPilot** [comment] 2016-11-15 15:38
It is printing the result out.  Unfortunately, a little too accurately.  It thinks that is an html tag.

**Comment by TakenPilot** [comment] 2016-11-15 15:41
Duplicate of https://github.com/yhat/rodeo/issues/535

**Closed by TakenPilot** 2016-11-15 15:41 UTC
Labels: bug
