### ISSUE TITLE
Turn into Brew formula? 

### ISSUE THREAD

**Issue by dalanmiller** [yhat/rodeo#39] opened 2015-04-24 04:19 UTC
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook

**Comment by ogrisel** [comment] 2015-04-24 10:45
This is a duplicate of #6.

**Comment by glamp** [comment] 2015-04-24 13:08
closing for dup

**Closed by glamp** 2015-04-24 13:08 UTC
