### ISSUE TITLE
The application "Rodeo" can't be opened

### ISSUE THREAD

**Issue by low-decarie** [yhat/rodeo#301] opened 2016-05-28 07:55 UTC
I have:
Python 2.7.11 :: Anaconda custom (x86_64)
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

I get the following errors when trying to launch Rodeo, even after a clean install:

`2016-05-28 8:52:12.296 AM Finder[668]: spawn_via_launchd() failed, errno=111 label=[0x0-0x6ae6ae].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1`

<img width="420" alt="screen shot 2016-05-28 at 8 50 49 am" src="https://cloud.githubusercontent.com/assets/806435/15625989/4d46130a-24b1-11e6-8ab9-8b1b7f8b36d3.png">

**Comment by TakenPilot** [comment] 2016-05-29 15:21
Ah, thanks!

Which version of Rodeo are you running?  I created a new process for signing the application for OSX with a single command, and also for auto-updating the application.  It might have a few bugs.  This new process is only for the version of the application that is downloadable from github, however.

The version available from the website is still using the old process and will probably work better.

**Comment by rforgione** [comment] 2016-06-07 16:33
I'm getting this one also -- ran into issues after downloading/installing 1.4.8 and then 1.4.7. Each one had the same error as the one screenshotted above.

**Comment by TakenPilot** [comment] 2016-06-07 17:07
That's really strange.  People around the office are installing the application on OSX from github and it seems to work as normal.  The application signing is being reported as "accepted" by Apple's codesign tool.  It has to be something else.

I'm really curious:
1) Are you able to install other applications from .dmg files?  Maybe there is a setting preventing non-Apple store apps from installing.
2) When you install the app, are you double-clicking the Rodeo icon, or are you dragging the Rodeo icon over into the folder?
3) If you go into your /Applications folder and right-click on Rodeo, are there any interesting options?

**Comment by TakenPilot** [comment] 2016-06-07 17:15
Oh, and:

4) Are you installing from the dmg file, or are you trying to install from one of the other files?

Try this link for the latest version:  bareback.s.yhat.com

We're going to use that link once we officially launch.

**Comment by rforgione** [comment] 2016-06-07 17:52
Hey @TakenPilot -- in order:

1. Yeah, other installations seem to be working fine
2. I'm dragging it over the the folder
3. Not really any interesting options
4. I'm installing from the dmg file

I'll give the link a shot. Thanks!

**Comment by coristig** [comment] 2016-06-08 12:37
Here are some logs from someone who had this same issue:

```08/06/16 09:35:08,882 lsd[317]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
08/06/16 09:35:08,899 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000016.Electron[3354]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Rodeo.app/Contents/MacOS/Electron
08/06/16 09:35:08,899 Finder[323]: spawn_via_launchd() failed, errno=111 label=[0x0-0x267267].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
08/06/16 09:35:08,899 Finder[323]: spawn_via_launchd() failed, errno=111 label=[0x0-0x267267].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1
08/06/16 09:35:08,990 lsd[317]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist```

**Comment by TakenPilot** [comment] 2016-06-09 15:35
If most people can open the app without warnings, I doubt it.  

Also as mentioned, the codesign app says that Rodeo is signed.

**Comment by ebonet** [comment] 2016-06-11 01:41
I am having this issue as well. Downloaded 1.4.8 from the link listed on github, dragged to the Applications folder tried to open it.

**Comment by ebonet** [comment] 2016-06-11 01:46
Update: I can open it normally by typing /Applications/Rodeo.app/MacOS/Contents/Rodeo

**Comment by ben519** [comment] 2016-06-12 18:05
I get this as well right after I update Rodeo from an older version, but after I restart my computer things work normally.

**Comment by glamp** [comment] 2016-06-13 13:50
@ebonet @ben519 Thanks for the details! Unfortunately I can't  reproduce (but don't worry I believe you) though I am suspecting something to do with the auto-updates--this is notoriously buggy on Electron.

We will dig in and figure out what's going on!

**Comment by akamlani** [comment] 2016-06-13 16:23
I'm experiencing the same issue now as well, when attempting to launch by command line (/usr/local/bin/rodeo .), I receive the following error:

LSOpenURLsWithRole() failed for the application /Applications/Rodeo.app with error -10810.

**Comment by leetrout** [comment] 2016-06-14 15:46
Same error here...

```
(yhat) faster:~ yhat$ open /Applications/Rodeo.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Rodeo.app.
```

Logs in console were

```
6/14/16 10:42:06.749 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000119.Electron[19209]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Rodeo.app/Contents/MacOS/Electron
6/14/16 10:42:06.749 AM Finder[252]: spawn_via_launchd() failed, errno=111 label=[0x0-0x296a968].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
6/14/16 10:42:06.749 AM Finder[252]: spawn_via_launchd() failed, errno=111 label=[0x0-0x296a968].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1
6/14/16 10:42:10.290 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x1000011a.Electron[19211]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Rodeo.app/Contents/MacOS/Electron
6/14/16 10:42:10.290 AM Alfred 2[327]: spawn_via_launchd() failed, errno=111 label=[0x0-0x296b969].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.main-thread
6/14/16 10:42:10.290 AM Alfred 2[327]: spawn_via_launchd() failed, errno=111 label=[0x0-0x296b969].com.yhat.rodeo path=/Applications/Rodeo.app/Contents/MacOS/Electron flags=1
```

Googling shows some similar errors related to java:
http://stackoverflow.com/questions/25139265/opening-app-on-mac-os-x-10-8-5-results-in-error-10658
http://stackoverflow.com/questions/19594627/open-java-applications-fail-silently-on-os-x-mavericks


Seems odd that it would be related to Java tho... I'll keep looking and see if we can find a common denominator....

My mac is:

```
(yhat) faster:~ yhat$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
(yhat) faster:~ yhat$ uname -a
Darwin faster.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

**Comment by leetrout** [comment] 2016-06-14 15:50
Also, `/Applications/Rodeo.app/Contents/MacOS/Rodeo` does run for me as well.

**Comment by leetrout** [comment] 2016-06-14 15:58
There is a comment https://github.com/atom/atom/issues/3093#issuecomment-208464425 that suggests renaming the executable could be to blame.

**Comment by TakenPilot** [comment] 2016-06-14 16:22
So based on the links that @leetrout found, it could either be:

1. Java on Mac interfering, or 
2. Apple GateKeeper getting confused if someone renames Rodeo to something else

Could someone with this problem confirm this?  I'm still trying to reproduce the issue locally on different machines.

**Comment by ben519** [comment] 2016-06-14 16:53
If it helps, I got this issue when I upgraded from Rodeo 1.3 to 1.4.9 and I'm on Mac OSX 10.11.5

**Comment by leetrout** [comment] 2016-06-14 19:09
@ben519 what happens if you run `sudo open /Applications/Rodeo.app` from the terminal?

**Comment by ben519** [comment] 2016-06-14 19:19
@leetrout `sudo open /Applications/Rodeo.app` opens Rodeo for me.  But as I mentioned, simply restarting my computer after installing Rodeo 1.4.9 prevented the "Application cannot be opened" prompt from appearing when I try to start Rodeo normally.

**Comment by ben519** [comment] 2016-06-14 19:20
@leetrout what version of Rodeo were you upgrading from and to?  For me it was 1.3 to 1.4.9.

**Comment by leetrout** [comment] 2016-06-14 19:29
@ben519 I did a clean install of 1.4.9 and rebooted and it still doesn't start for me.

**Comment by TakenPilot** [comment] 2016-06-14 20:01
To give more context to this bug:

https://github.com/electron-userland/electron-packager/issues/323

http://www.openradar.me/23614087

> Gatekeeper (syspolicyd) becomes confused when an .app bundle it assessed previously changes such that its CFBundleExecutable’s name is different.

Two months ago Electron builder had to change the name of the executable in Electron apps to match the name of the app, due to Apple becoming more strict with code signing.  When someone has the app installed and an auto-update causes this name to change, GateKeeper becomes confused.

### To fix:

Create a symlink to where GateKeeper thinks the binary is.  Run Rodeo once.  The auto-update will delete the symlink, and Rodeo will continue to work forever on.

```bash
cd /Applications/Rodeo.app/Contents/MacOS/ && ln -s Rodeo Electron
```

This will only affect users that discovered the secret pre-release Rodeo from Github and received the auto-update that suddenly changed that name.  Anyone have good ideas for how we can tell those specific users about this fix?

**Comment by TakenPilot** [comment] 2016-06-14 20:11
I'm going to tentatively close this issue.  If this issue comes back in a different form, let's create a new thread because it'll be from a different cause.

**Closed by TakenPilot** 2016-06-14 20:11 UTC
Labels: bug

**Comment by joeferraro** [comment] 2016-06-15 15:24
I ran into this as well and can confirm a restart worked for me. Thanks for the detailed breakdown and documentation @TakenPilot
