### ISSUE TITLE
Save font preferences

### ISSUE THREAD

**Issue by scottdonnelly** [yhat/rodeo#217] opened 2016-01-02 10:59 UTC
Minor thing... but every time I restart Rodeo it forgets my font preference and starts in Helvetica.

It remembers the theme and editor styles I chose though.

Using Ubuntu desktop 14.04.

**Comment by coristig** [comment] 2016-01-05 17:05
Thanks Scott,

I believe this is a duplicate of this [issue](https://github.com/yhat/rodeo/issues/210)

Closing

**Closed by coristig** 2016-01-05 17:05 UTC
