### ISSUE TITLE
1.4.9 Release Defects

### ISSUE THREAD

**Issue by akamlani** [yhat/rodeo#335] opened 2016-06-12 15:57 UTC
I've noticed a few initial items in release 1.4.9:
## Defects
* the help submenu is missing, so you are not able to launch a help on a function (e.g. np.random.binomial?)
* the console always starts at Root, regardless of the session directory being set
* the release seems to draw more power from my battery on a MacBook Pro than previous releases.

## Requests
* While not a defect, I think it would be good if the variables in the Environment Window would be shown, similar to has it is in "RStudio".

**Comment by TakenPilot** [comment] 2016-06-17 02:25
Thanks for the feedback!

The defects that you've listed are true.

The battery power issue has been somewhat resolved in version 2.0.2.

The console issue has been noted elsewhere but not in a very clear way.  It would be useful to have an Issue to link to, so that when the Issue is fixed we can close it.

The help menu is a feature that has been [temporarily removed](http://discuss.yhat.com/t/some-feature-is-missing/63), but it will be back.

**Closed by TakenPilot** 2016-06-17 02:25 UTC
